---
- name: Configuring EIGRP on Router 2
  hosts: R2
  gather_facts: false
  connection: local

  tasks:
    - name: Adding an IP to host
      ios_config:
        lines:
          - ip address 192.168.20.1 255.255.255.0
        parents: interface F0/0

    - name: Configuring EIGRP on Router 2
      ios_config:
        lines:
          - network 10.10.10.2
        parents: router eigrp 333

- name: Configuring EIGRP on Router 1
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
    - name: Adding an IP to host
      ios_config:
        lines:
          - ip address 192.168.10.1 255.255.255.0
        parents: interface F0/0

    - name: Configuring EIGRP on Router 1
      ios_config:
        lines:
          - network 10.10.10.1
        parents: router eigrp 333